// Social media icon URLs (using reliable CDN - PNG format for email compatibility)
export const socialIcons = {
  facebook: 'https://cdn-icons-png.flaticon.com/32/733/733547.png',
  facebookCircle: 'https://cdn-icons-png.flaticon.com/32/145/145802.png',
  twitter: 'https://cdn-icons-png.flaticon.com/32/733/733579.png', // Old Twitter logo (kept for compatibility)
  x: '/icons/download.png', // Official X logo - local file
  linkedin: 'https://cdn-icons-png.flaticon.com/32/733/733561.png',
  linkedinCircle: 'https://cdn-icons-png.flaticon.com/32/174/174857.png',
  instagram: 'https://cdn-icons-png.flaticon.com/32/2111/2111463.png', // Clean Instagram logo (gradient preserved)
  instagramCircle: 'https://cdn-icons-png.flaticon.com/32/2111/2111463.png', // Same clean logo for circle
  youtube: 'https://cdn-icons-png.flaticon.com/32/1384/1384060.png', // Red YouTube logo (proper red color)
  pinterest: 'https://cdn-icons-png.flaticon.com/32/145/145808.png',
  github: 'https://cdn-icons-png.flaticon.com/32/733/733553.png',
  dribbble: 'https://cdn-icons-png.flaticon.com/32/733/733544.png',
  behance: 'https://cdn-icons-png.flaticon.com/32/733/733537.png',
  tiktok: 'https://cdn-icons-png.flaticon.com/32/3046/3046121.png',
  phone: 'https://cdn-icons-png.flaticon.com/32/724/724664.png',
  phoneCircle: 'https://cdn-icons-png.flaticon.com/32/455/455705.png',
  mobile: 'https://cdn-icons-png.flaticon.com/32/0/191.png',
  email: 'https://cdn-icons-png.flaticon.com/32/561/561127.png',
  emailOutline: 'https://cdn-icons-png.flaticon.com/32/542/542689.png',
  website: 'https://cdn-icons-png.flaticon.com/32/1006/1006771.png',
  websiteGlobe: 'https://cdn-icons-png.flaticon.com/32/1239/1239682.png',
  location: 'https://cdn-icons-png.flaticon.com/32/684/684908.png',
  locationPin: 'https://cdn-icons-png.flaticon.com/32/684/684809.png',
  calendar: 'https://cdn-icons-png.flaticon.com/32/2693/2693507.png',
  portfolio: 'https://cdn-icons-png.flaticon.com/32/3135/3135715.png',
  briefcase: 'https://cdn-icons-png.flaticon.com/32/3281/3281307.png',
};

export const templates = {
  // Template 1: Gradient Sidebar (Jasmine Williams style)
  gradientSidebar: {
    id: 'gradientSidebar',
    name: 'Gradient Pro',
    description: 'Photo with gradient sidebar',
    layout: 'gradientSidebar',
    color: '#0d7377',
    fontFamily: 'Arial, sans-serif',
  },
  // Template 2: Orange Banner (Angle Nancy style)
  orangeBanner: {
    id: 'orangeBanner',
    name: 'Orange Banner',
    description: 'Bold colors, framed photo',
    layout: 'orangeBanner',
    color: '#e67e22',
    fontFamily: 'Arial, sans-serif',
  },
  // Template 3: Yellow Hexagon (Thomas Smith style)
  yellowHexagon: {
    id: 'yellowHexagon',
    name: 'Yellow Modern',
    description: 'Contact grid, logo area',
    layout: 'yellowHexagon',
    color: '#d4a00a',
    fontFamily: 'Arial, sans-serif',
  },
  // Template 4: Blue Modern (Edward Richards style)
  blueModern: {
    id: 'blueModern',
    name: 'Blue Corporate',
    description: 'Large photo, modern grid',
    layout: 'blueModern',
    color: '#2563eb',
    fontFamily: 'Arial, sans-serif',
  },
  // Template 5: Black Footer (Andie Edmond style)
  blackFooter: {
    id: 'blackFooter',
    name: 'Elegant Dark',
    description: 'Square photo, dark social bar',
    layout: 'blackFooter',
    color: '#1a1a1a',
    fontFamily: 'Arial, sans-serif',
  },
  // Template 6: Script Elegant (Melissa Johnson style)
  scriptElegant: {
    id: 'scriptElegant',
    name: 'Script Elegant',
    description: 'Script signature, branding',
    layout: 'scriptElegant',
    color: '#2c3e50',
    fontFamily: 'Arial, sans-serif',
    nameFontFamily: "'Dancing Script', cursive",
  },
  // Template 7: Red Circle (Jenny McBride style)
  redCircle: {
    id: 'redCircle',
    name: 'Red Circle',
    description: 'Bordered photo, script name',
    layout: 'redCircle',
    color: '#c53030',
    fontFamily: 'Arial, sans-serif',
    nameFontFamily: "'Dancing Script', cursive",
  },
  // Template 8: Simple Photo (Kelly Richardson style)
  simplePhoto: {
    id: 'simplePhoto',
    name: 'Simple Clean',
    description: 'Circular photo, labeled info',
    layout: 'simplePhoto',
    color: '#333333',
    fontFamily: 'Arial, sans-serif',
  },
  // Original templates kept for backwards compatibility
  corporateRed: {
    id: 'corporateRed',
    name: 'Corporate Red',
    description: 'Two-column, social icons',
    layout: 'twoColumnWithLogo',
    color: '#B91C1C',
    fontFamily: 'Arial, sans-serif',
  },
  elegantMinimal: {
    id: 'elegantMinimal',
    name: 'Elegant Minimal',
    description: 'Large photo, vertical separator',
    layout: 'photoSidebar',
    color: '#1a1a1a',
    fontFamily: 'Arial, sans-serif',
  },
  corporateGreen: {
    id: 'corporateGreen',
    name: 'Creative Writer',
    description: 'Word-focused, elegant design',
    layout: 'creativeWriter',
    color: '#2F6B3E',
    fontFamily: 'Arial, sans-serif',
  },
  scriptPersonal: {
    id: 'scriptPersonal',
    name: 'Script Personal',
    description: 'Script font, circular photo',
    layout: 'photoWithScript',
    color: '#4a4a4a',
    fontFamily: 'Arial, sans-serif',
    nameFontFamily: "'Dancing Script', cursive",
  },
};

export const applyTemplate = (templateKey, currentData) => {
  const template = templates[templateKey];
  if (!template) return currentData;

  return {
    ...currentData,
    template: templateKey,
    color: template.color,
  };
};

// Sample profiles for freelancers - MORE OPTIONS
export const sampleProfiles = {
  // 1. UI/UX Designer - Gradient Pro
  jasmineDesigner: {
    name: 'Jasmine Williams',
    specialty: 'Freelance UI/UX Designer',
    company: 'FOREVER DESIGNS LLC',
    phone: '+1 (555) 837-7059',
    mobile: '+1 (555) 669-3132',
    email: 'jasmine@foreverdesigns.co',
    website: 'www.foreverdesigns.co',
    address: 'Level 27, 7485 Shore Ave, Chicopee, MA 01020, USA',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    template: 'gradientSidebar',
    color: '#0d7377',
    hourlyRate: '$95/hour',
    availability: 'Available for projects',
    bookingUrl: 'https://calendly.com/jasmine',
    portfolioUrl: 'https://dribbble.com/jasmine',
    socialLinks: {
      facebook: 'https://facebook.com',
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
      instagram: 'https://instagram.com',
    },
  },
  // 2. Marketing Consultant - Script Elegant
  melissaAgent: {
    name: 'Melissa Johnson',
    specialty: 'Freelance Marketing Consultant',
    company: '',
    companyScript: 'Marketing Magic',
    phone: '000.123.1212',
    mobile: '888.123.3245',
    email: 'hello@melissajohnson.com',
    website: 'www.melissajohnson.com',
    address: '123 Street Ave. Palm Springs, CA 002312',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
    template: 'scriptElegant',
    color: '#2c3e50',
    hourlyRate: '$150/hour',
    availability: '2 spots left this month',
    bookingUrl: 'https://calendly.com/melissa',
    socialLinks: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      tiktok: 'https://tiktok.com',
    },
  },
  // 3. Web Developer - Red Circle
  jennyDev: {
    name: 'Jenny McBride',
    specialty: 'Freelance Web Developer',
    company: 'BRIGHT CODE',
    phone: '(627) 332-9018',
    email: 'jenny.mcbride@gimm.io',
    website: 'www.gimm.io',
    address: '112 Econome Ct, Folsom, CA 95630',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    template: 'redCircle',
    color: '#c53030',
    hourlyRate: '$120/hour',
    availability: 'Accepting new clients',
    bookingUrl: 'https://calendly.com/jenny',
    portfolioUrl: 'https://github.com/jenny',
    socialLinks: {
      dribbble: 'https://dribbble.com',
      instagram: 'https://instagram.com',
      linkedin: 'https://linkedin.com',
    },
  },
  // 4. Virtual Assistant - Simple Photo
  kellyAdmin: {
    name: 'Kelly Richardson',
    specialty: 'Virtual Assistant',
    phone: '+615.8485.684.45',
    email: 'info@kellyva.com',
    website: 'www.kellyva.com',
    address: 'Davis Patrick P.O. Sociosqu Rd. Bethlehem Utah',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    template: 'simplePhoto',
    color: '#333333',
    hourlyRate: '$45/hour',
    availability: 'Available immediately',
    bookingUrl: 'https://calendly.com/kelly',
    socialLinks: {
      facebook: 'https://facebook.com',
      twitter: 'https://twitter.com',
      instagram: 'https://instagram.com',
      pinterest: 'https://pinterest.com',
    },
  },
  // 5. Graphic Designer - Orange Banner
  angleDesigner: {
    name: 'Angle Nancy',
    specialty: 'Graphic Designer',
    company: 'YOUR LOGO SLOGAN',
    phone: '000 123 456 789',
    email: 'yourwebsite@ymail.com',
    website: 'www.yourwebsite.com',
    address: '4821 Ridge Top Cir, Anchorage, Alaska 99508, USA',
    photoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=face',
    template: 'orangeBanner',
    color: '#e67e22',
    hourlyRate: '$80/hour',
    availability: 'Open for projects',
    bookingUrl: 'https://calendly.com/angle',
    portfolioUrl: 'https://behance.net/angle',
    socialLinks: {
      youtube: 'https://youtube.com',
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
      behance: 'https://behance.net',
      facebook: 'https://facebook.com',
    },
  },
  // 6. Illustrator - Yellow Hexagon
  thomasIllustrator: {
    name: 'Thomas Smith',
    specialty: 'Freelance Illustrator',
    company: '',
    phone: '+000 123 456 7890',
    mobile: '+000 123 456 7890',
    email: 'name@gmail.com',
    website: 'www.websitename.com',
    address: 'your street address here, new york city zip code - 000',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    template: 'yellowHexagon',
    color: '#d4a00a',
    hourlyRate: '$70/hour',
    availability: 'Taking commissions',
    portfolioUrl: 'https://dribbble.com/thomas',
    socialLinks: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com',
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
    },
  },
  // 7. Restaurant Consultant - Blue Modern
  edwardConsultant: {
    name: 'Edward Richards',
    specialty: 'Restaurant Consultant',
    company: 'TechGrid',
    phone: '(671) 555-0110',
    email: 'e.richards@email.com',
    website: 'www.techgrid.com',
    address: '4517 Washington Ave. Manchester, Kentucky 39495',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    template: 'blueModern',
    color: '#2563eb',
    hourlyRate: '$200/hour',
    availability: 'Limited availability',
    bookingUrl: 'https://calendly.com/edward',
    socialLinks: {
      facebook: 'https://facebook.com',
      twitter: 'https://twitter.com',
      instagram: 'https://instagram.com',
      tiktok: 'https://tiktok.com',
      youtube: 'https://youtube.com',
    },
  },
  // 8. Boutique Owner - Black Footer
  andieOwner: {
    name: 'Andie Edmond',
    specialty: 'Owner of Bajor Boutique',
    phone: '000.123.1212',
    mobile: '888.123.3245',
    email: 'hello@yourwebsite.com',
    website: 'www.yourwebsite.com',
    photoUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&h=200&fit=crop&crop=face',
    template: 'blackFooter',
    color: '#1a1a1a',
    hourlyRate: 'Project-based',
    availability: 'Accepting inquiries',
    socialLinks: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com',
      pinterest: 'https://pinterest.com',
      twitter: 'https://twitter.com',
      youtube: 'https://youtube.com',
      linkedin: 'https://linkedin.com',
      tiktok: 'https://tiktok.com',
    },
  },
  // 9. Copywriter - Corporate Green
  alexCopywriter: {
    name: 'Alex Rivera',
    specialty: 'Freelance Copywriter',
    company: 'WordCraft Studio',
    phone: '+1 (555) 234-5678',
    mobile: '+1 (555) 876-5432',
    email: 'alex@wordcraft.co',
    website: 'www.wordcraft.co',
    address: '789 Creative Blvd, Austin, TX 78701',
    template: 'corporateGreen',
    color: '#2F6B3E',
    hourlyRate: '$85/hour',
    availability: 'Available for retainers',
    bookingUrl: 'https://calendly.com/alex',
    socialLinks: {
      linkedin: 'https://linkedin.com',
      twitter: 'https://twitter.com',
    },
  },
  // 10. Photographer - Elegant Minimal
  sarahPhotographer: {
    name: 'Sarah Chen',
    specialty: 'Portrait Photographer',
    company: 'CHEN PHOTOGRAPHY',
    tagline: 'CAPTURING MOMENTS',
    phone: '+1 (555) 987-6543',
    email: 'sarah@chenphotography.com',
    website: 'www.chenphotography.com',
    address: '456 Art District, San Francisco, CA 94102',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    template: 'elegantMinimal',
    color: '#1a1a1a',
    hourlyRate: '$250/session',
    availability: 'Booking for Spring',
    bookingUrl: 'https://calendly.com/sarah',
    portfolioUrl: 'https://instagram.com/sarahchen',
    socialLinks: {
      instagram: 'https://instagram.com',
    },
  },
};
